INSERT OR IGNORE INTO grab_platforms (code, name, brand, icon_slug, enabled) VALUES
  ('zhihu',        '知乎',         '0084FF', 'zhihu',        0),
  ('xiaoyuzhou',   '小宇宙',       '6B4EFF', NULL,           0),
  ('dewu',         '得物',         '000000', NULL,           0),
  ('kuaishou',     '快手',         'FF6E00', 'kuaishou',     0),
  ('taobao',       '淘宝',         'FF5000', 'taobao',       0),
  ('jd',           '京东',         'E1251B', NULL,           0),
  ('pinduoduo',    '拼多多',       'E02E24', NULL,           0),
  ('zsxq',         '知识星球',     '00B26F', NULL,           0),
  ('baidu',        '百度',         '2932E1', 'baidu',        0),
  ('telegram',     'Telegram',     '26A5E4', 'telegram',     0),
  ('whatsapp',     'WhatsApp',     '25D366', 'whatsapp',     0),
  ('twitch',       'Twitch',       '9146FF', 'twitch',       0),
  ('facebook',     'Facebook',     '1877F2', 'facebook',     0),
  ('instagram',    'Instagram',    'E4405F', 'instagram',    0),
  ('youtube',      'YouTube',      'FF0000', 'youtube',      0),
  ('twitter',      'X (Twitter)',  '000000', 'x',            0),
  ('threads',      'Threads',      '000000', 'threads',      0),
  ('linkedin',     'LinkedIn',     '0A66C2', NULL,           0);
